### ISSUE TITLE
[Bug]: Markdown not working

### ISSUE THREAD

**Issue by AR-Student824** [MarketingPipeline/Markdown-Tag#10] opened 2022-06-14 06:46 UTC
### Contact Details

arcodez@protonmail.com

### What happened?

I tried using Markdown-tag and it was not working, everything was a codeblock. So, to check if it was an error with my code, I tried deploying the exact code in the `index.html` of this exact repository and it would result in the same bug. Below is an image of what I see: 
![image](https://user-images.githubusercontent.com/74219764/173511083-43fc8f7e-5aef-432e-897f-e6e5970dd6b3.png)

Please check if you can reproduce this bug

### What type of browser are you seeing the problem on?

- Brave Browser Nightly on Windows 11
- Google Chrome on Android 12

_Both produce the same problem_

### Code to produce this issue.

**Check the index.html file of this repository**

**Comment by AR-Student824** [comment] 2022-06-14 06:51
@MarketingPip

**Comment by MarketingPip** [comment] 2022-06-14 08:09
@AR-Student824 - can you give some insight to what your console log is saying, if anything? And to verify, you are using the script at the bottom of your HTML document?

It appears things are working fine on my end - please look at this JSFiddle [here](https://jsfiddle.net/cm7ojt2f/) and let know if any issues still on your end arise or if it was just due to user error please & thank you! :+1:

**Comment by AR-Student824** [comment] 2022-06-16 02:59
> @AR-Student824 - can you give some insight to what your console log is saying, if anything? And to verify, you are using the script at the bottom of your HTML document?
> 
> It appears things are working fine on my end - please look at this JSFiddle [here](https://jsfiddle.net/cm7ojt2f/) and let know if any issues still on your end arise or if it was just due to user error please & thank you! 👍

This is the only warning in the console
![image](https://user-images.githubusercontent.com/74219764/173981534-5348fccc-e71d-4778-b702-a8469b8ef054.png)

And as far the script goes, like I said, the code is exactly the same as your index.html file so whatever is in there is in mine, so I don't think that is the issue.

**Comment by MarketingPip** [comment] 2022-06-16 04:02
@AR-Student824 can you post a JS fiddle?

**Comment by AR-Student824** [comment] 2022-06-16 06:55
@MarketingPip can you just check the index.html file in this exact repository as I am running the exact same code to test

**Comment by MarketingPip** [comment] 2022-06-16 06:57
@AR-Student824  - already have. I have linked you above the script working fine in a JSfiddle. Please look at it.

**Comment by AR-Student824** [comment] 2022-06-16 07:01
> @AR-Student824  - already have. I have linked you above the script working fine in a JSfiddle. Please look at it. It is the index.html file running. 

you can look at my site for a reference 
https://www.formrocket.me/docs/index.html

it's running the exact code shown in your demo, which you can review by viewing the source also

**Comment by AR-Student824** [comment] 2022-06-16 07:02
do note I added the codeblock on top with highlightjs and it results with the same problem even without it

**Comment by AR-Student824** [comment] 2022-06-16 07:04
some of it does work at the bottom but not all of it

**Comment by MarketingPip** [comment] 2022-06-16 08:44
@AR-Student824  - this is due to user error I do believe with your Markdown indentation. I have put two resources in the JSFiddle for you to help you fix your problems! Please look at this & confirm.  [JSFiddle](https://jsfiddle.net/z40mkdcp/2/) 

The JS Fiddle should help you - 
* Add syntax highlighting support for your project .
* Understand what you are doing wrong (I believe)

I will leave this open - till we get this confirmed as solved. But I do believe this should fix your issue. Let me know! :+1:

**Comment by AR-Student824** [comment] 2022-06-17 02:53
Yes, I understand what you are trying to say, but also in your index.html file, you are also putting indentations, so I'd suggest you change that to avoid confusion. Other than that, thank you!

**Comment by AR-Student824** [comment] 2022-06-17 02:53
Yes, I understand what you are trying to say, but also in your index.html file, you are also putting indentations, so I'd suggest you change that to avoid confusion. Other than that, thank you @MarketingPip

**Comment by MarketingPip** [comment] 2022-06-17 04:49
Ah I see what you are saying now! My apologizes! There is an update for Markdown Tag (shortly) on the way - I do believe @DarkenLM has addressed this issue (correct Markdown indentation format) if I am not mistaken. Hopefully @DarkenLM - can provide some insight regarding this in the coming update for you.

**Comment by DarkenLM** [comment] 2022-06-24 07:30
I came across this problem myself during the port of MarkdownTag to a WebComponent, but haven't added any solution yet.
The biggest problem of all is that the DOM does not store the indentation level of the elements as written in the HTML file, and instead returns an Element Tree, and the only way to get indentation I can think of would be to add a preprocessor, which would go against the current model of MarkdownTag.

There is a hacky way to get the original HTML code delivered by the server before any js files kick in, but the biggest problem of them all in that solution would be locating the correct MDTag instance, which would be really hard, considering many tags may have the same contents.

The closest solution I could come with, even though not properly tested, would be to add a step before generating the HTML where the code calculates the minimum amount of indent the string has by reading it line by line and getting the whitespace behind the text inside each one. It will require some time (which I currently don't have) to perfect it, but is doable.

**Comment by MarketingPip** [comment] 2022-06-25 22:41
@DarkenLM - I was playing with something last night and was thinking of something. Realistically we can't implement this. As how are we supposed to know if a line indented is supposed to be a code block or H1 etc. (Hope this makes sense to you) 

I think we just need to better document the usage for future users indicating the tag and content should start at the left side of their HTML document.

**Comment by MarketingPip** [comment] 2022-07-06 03:09
Closing this for now as this is not really an issue with Markdown-Tag, but as of now - more of a issue with the documentation of the usage of the current version of Markdown-Tag. 

Tho you can maybe expect a feature that takes care of auto indentation in future.

**Closed by MarketingPip** 2022-07-06 03:09 UTC
Labels: bug
